// <auto-generated />
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ExcelPreviewContext))]
    [Migration("20251229101935_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.ExcelData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ExcelDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "01KDMSXN7FV3S9FK4TRNXZHP8Z",
                            Value = "67"
                        },
                        new
                        {
                            Id = 2,
                            Name = "01KDMSXN7FAKWQTMFRPHP52PAX",
                            Value = "15"
                        },
                        new
                        {
                            Id = 3,
                            Name = "01KDMSXN7FHA3JQEDK7W97W71N",
                            Value = "13"
                        },
                        new
                        {
                            Id = 4,
                            Name = "01KDMSXN7F7MDQZKC6XNCBP3R4",
                            Value = "53"
                        },
                        new
                        {
                            Id = 5,
                            Name = "01KDMSXN7FRR1FCPPQ7T7ZMPFA",
                            Value = "17"
                        },
                        new
                        {
                            Id = 6,
                            Name = "01KDMSXN7FWTE92R14CM2D0RN5",
                            Value = "27"
                        },
                        new
                        {
                            Id = 7,
                            Name = "01KDMSXN7F0PHDAZTKHWAMTR8M",
                            Value = "73"
                        },
                        new
                        {
                            Id = 8,
                            Name = "01KDMSXN7F3ZHTJTRPBC4BY82E",
                            Value = "52"
                        },
                        new
                        {
                            Id = 9,
                            Name = "01KDMSXN7FYTQ9RPWFDETQ2TBP",
                            Value = "18"
                        },
                        new
                        {
                            Id = 10,
                            Name = "01KDMSXN7FTT2A3X5XPZBP331T",
                            Value = "77"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
